---
abstract: 'Check for presence of dependencies'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::CheckDeps: 0.002
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-CheckDeps
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::PrereqSource: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Test::CheckDeps: 0.002
  Test::More: 0.94
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Test-CheckDeps
  repository: git://github.com/karenetheridge/dist-zilla-plugin-test-checkdeps.git
version: 0.006
